### ISSUE TITLE
Need Ingress Support

### ISSUE THREAD

**Issue by jmckind** [jmckind/argocd-operator#26]
The operator should support creating Ingress resources, similar to the Route behaviour when running in OpenShift.

**Comment by jmckind** [comment]
Working on this in https://github.com/jmckind/argocd-operator/tree/ingress

**Comment by disposab1e** [comment]
Here is an example from the argo-cd Slack channel yesterday with comment.. this works great in ingress nginx:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  rules:
  - host: argocd.<redacted>.net
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https
        path: /
  tls:
  - hosts:
    - argocd.<redacted>.net
    secretName: argocd-secret # this is provided by Argo CD
```
