### ISSUE TITLE
Enable Operator deployment in RBAC enabled Kubernetes cluster

### ISSUE THREAD

**Issue by disposab1e** [jmckind/argocd-operator#27]
Without ``namespaces`` as resource for apiGroups "" the operator will not deploy in RBAC enabled Kubernetes Cluster. Tested with GCP.

```
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - services/finalizers
  - endpoints
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
```
