### ISSUE TITLE
Ingress Tests

### ISSUE THREAD

**Issue by disposab1e** [jmckind/argocd-operator#34]
Test Scenario: (new builds, push, bundle from master)
- OLM Install
- Ingress

Finding: 
ServiceAccount ``argocd-operator``missing permissions in CSV and role.yaml.
```
         - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - '*'
```
Throw in a PR when all tests are finished.

**Comment by disposab1e** [comment]
No reconcilation started when I change the example ArgoCD instance via Web UI.

I'm not sure it's implemented but there is no reconcilation at the moment. Tested with following values:

 ```
server:
    insecure: true/false
    service:
      type: LoadBalancer/ClusterIP
```
```
  ingress:
    enabled: true/false
  server:
    insecure:
      true/false
```

**Comment by disposab1e** [comment]
Summary:

```
server:
   insecure: false
   service:
     type: LoadBalancer
```
Tested in GKE: awesome! (Web UI + CLI) 

```
ingress:
    enabled: true
  server:
    insecure:
      true
```
Tested in Minikube: awesome! (Web UI + CLI) 
Tested in GKE: Both ingresses created but not usable.
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
} 
```
I think this is because of GKE security and not a problem of the operator.
